version: '3'
services:
  app:
    hostname: ${STATIC_SITE_HOSTNAME}
    build:
      context: app
      dockerfile: ./Dockerfile
    image: arrrspace-app
    ports:
      - "${STATIC_SITE_HOSTPORT}:80"
  testsvc:
    hostname: test.svc
    build:
      context: testSvc
      dockerfile: ./Dockerfile
    image: arrrspace-testsvc
    networks:
      - eg
    expose:
      - "3000"
  authsvc:
    hostname: auth.svc
    build:
      context: authSvc
      dockerfile: ./Dockerfile
    image: arrrspace-authsvc
    networks:
      - eg
    expose:
      - "3000"
  profilesvc:
    hostname: profile.svc
    build:
      context: profileSvc
      dockerfile: ./Dockerfile
    image: arrrspace-profilesvc
    networks:
      - eg
      - int
    expose:
      - "3000"
  feedsvc:
    hostname: feed.svc
    build:
      context: feedSvc
      dockerfile: ./Dockerfile
    image: arrrspace-feedsvc
    networks:
      - eg
    expose:
      - "3000"
  simplestoragesvc:
    hostname: simplestorage.svc
    build:
      context: simpleStorage
      dockerfile: ./Dockerfile
    image: simple-storagesvc
    networks:
      - int
    expose:
      - "9000"
  gateway:
    hostname: ${GATEWAY_HOSTNAME}
    build:
      context: gateway
      dockerfile: ./Dockerfile
    image: arrrspace-gateway
    ports:
      - "${GATEWAY_HOST_PORT}:8080"
    links:
      - testsvc:test.svc
    environment:
      - GATEWAY_HOSTNAME=${GATEWAY_HOSTNAME}
      - STATIC_SITE_HOSTNAME=${STATIC_SITE_HOSTNAME}
    networks:
      - eg
networks:
  eg:
  int: