version: '3'
services:
  app:
    hostname: ${STATIC_SITE_HOSTNAME}
    build:
      context: arrrspaceApp
      dockerfile: ./Dockerfile
    image: arrrspace-app
    ports:
      - "${STATIC_SITE_HOSTPORT}:80"    
  testsvc:
    hostname: test.svc
    build:
      context: testSvc
      dockerfile: ./Dockerfile
    image: arrrspace-testsvc
    networks:
      - eg
    expose:
      - "3000"
  gateway:
    hostname: ${GATEWAY_HOSTNAME}
    build:
      context: arrrspaceGateway
      dockerfile: ./Dockerfile
    image: arrrspace-gateway
    ports:
      - "${GATEWAY_HOST_PORT}:8080"
    links:
      - testsvc:test.svc
    environment:
      - GATEWAY_HOSTNAME=${GATEWAY_HOSTNAME}
      - STATIC_SITE_HOSTNAME=${STATIC_SITE_HOSTNAME}
    networks:
      - eg
networks:
  eg:
