apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: gateway
subjects:
  - kind: ServiceAccount
    namespace: default
    name: gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gateway
