apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: authsvc
  name: authsvc
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: authsvc
    spec:
      containers:
      - image: arrrspace-authsvc
        name: authsvc
        resources: {}
      hostname: auth.svc
      restartPolicy: Always
status: {}
