apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: deploy-manger-rolebinding
subjects:
  - kind: ServiceAccount
    namespace: default
    name: deploy-manager-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deploy-manager-role
