apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: feedsvc
  name: feedsvc
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: feedsvc
    spec:
      containers:
        - image: arrrspace-feedsvc:v1
          name: feedsvc
          resources: {}
      restartPolicy: Always
status: {}
