apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplestoragesvc
  labels:
    app: simplestoragesvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplestoragesvc
  template:
    metadata:
      labels:
        app: simplestoragesvc
    spec:
      containers:
        - name: simplestoragesvc
          image: arrrspace-simplestorage:v1
          env:
            - name: MINIO_ACCESS_KEY
              value: accesskey
            - name: MINIO_SECRET_KEY
              value: secretkey
          ports:
            - name: 'http'
              containerPort: 9000
      restartPolicy: Always
