http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  testapi:
    host: '*'
    paths: ['/test/:name']
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
serviceEndpoints:
  testsvc:
    url: "http://test.svc:3000"
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - rewrite
pipelines:
  default:
    apiEndpoints:
      - testapi
    policies:
      -
        rewrite:
          condition:
            name: pathmatch
            match: '/test/:name'
          action:
            rewrite: '/hello/:name'
      -
        proxy:
          -
            action:
              serviceEndpoint: testsvc
  # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
