http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  profile:
    host: '*'
    paths: ['/profile/*']
  feed:
    host: '*'
    paths: ['/feed/*']
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
serviceEndpoints:
  profilesvc:
    url: "http://profilesvc:3000"
  feedsvc:
    url: "http://feedsvc:3000"
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - rewrite
pipelines:
  feed:
    apiEndpoints:
      - feed
    policies:
      -
        log:
          - action:
              message: ${req.method} ${req.originalUrl}
      -
        rewrite:
          -
            condition:
              name: regexpmatch
              match: ^/feed/(.*)$
            action:
              rewrite: /$1
      -
        proxy:
          -
            action:
              serviceEndpoint: feedsvc
  profile:
    apiEndpoints:
      - profile
    policies:
      -
        rewrite:
          -
            condition:
              name: regexpmatch
              match: ^/profile/(.*)$
            action:
              rewrite: /$1
      -
        proxy:
          -
            action:
              serviceEndpoint: profilesvc
  # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
